#!/usr/bin/env node
/**
 * agent-init
 * Scaffolds a new agent-driven development project.
 * Usage: npx agent-init [project-name]
 *   or:  node agent-init.js [project-name]
 *
 * What it does:
 *   1. Creates project directory
 *   2. Generates PLAN.md from template (with date + project name pre-filled)
 *   3. Copies all agent prompt .md files into /agents/
 *   4. Creates cycle-state.json with initial state
 *   5. Prints next steps
 */

const fs = require("fs");
const path = require("path");

// ─── Config ──────────────────────────────────────────────────────────────────

const AGENT_FILES = [
  "agent-orchestrator.md",
  "agent-pm.md",
  "agent-design.md",
  "agent-frontend.md",
  "agent-backend.md",
  "agent-qa.md",
];

const INITIAL_CYCLE_STATE = {
  phase: "init",
  completed: [],
  pending: ["pm"],
  blockers: [],
  artifacts: {
    "PLAN.md": false,
    "design-spec.md": false,
    "api-contract.md": false,
    "qa-report.md": false,
  },
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function today() {
  return new Date().toISOString().split("T")[0];
}

function colorize(text, code) {
  return `\x1b[${code}m${text}\x1b[0m`;
}

const green = (t) => colorize(t, "32");
const cyan = (t) => colorize(t, "36");
const yellow = (t) => colorize(t, "33");
const bold = (t) => colorize(t, "1");

function log(msg) {
  console.log(msg);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function main() {
  const projectName = process.argv[2];

  if (!projectName) {
    console.error("Usage: agent-init <project-name>");
    console.error("Example: agent-init my-todo-app");
    process.exit(1);
  }

  // Sanitize project name for directory
  const dirName = projectName
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");

  const projectDir = path.join(process.cwd(), dirName);
  const agentsDir = path.join(projectDir, "agents");

  // 1. Create project directory
  if (fs.existsSync(projectDir)) {
    console.error(`Error: Directory "${dirName}" already exists.`);
    process.exit(1);
  }

  fs.mkdirSync(projectDir, { recursive: true });
  fs.mkdirSync(agentsDir, { recursive: true });
  log(green(`✓`) + ` Created ${dirName}/`);
  log(green(`✓`) + ` Created ${dirName}/agents/`);

  // 2. Generate PLAN.md from template
  const templatePath = path.join(__dirname, "PLAN.template.md");

  let planContent;
  if (fs.existsSync(templatePath)) {
    planContent = fs.readFileSync(templatePath, "utf8");
  } else {
    // Inline minimal fallback if template not found
    planContent = `# PLAN.md — ${projectName}\n> Generated by agent-init on ${today()}\n\n## Overview\n[TODO]\n\n## Goals\n- [ ] [TODO]\n\n## User Stories\n[TODO]\n\n## Technical Constraints\n[TODO]\n`;
  }

  // Replace placeholder values
  planContent = planContent
    .replace("[Project Name]", projectName)
    .replace("[DATE]", today());

  fs.writeFileSync(path.join(projectDir, "PLAN.md"), planContent);
  log(green(`✓`) + ` Generated PLAN.md`);

  // 3. Copy agent prompt files
  let copiedAgents = 0;
  for (const agentFile of AGENT_FILES) {
    const src = path.join(__dirname, agentFile);
    const dest = path.join(agentsDir, agentFile);

    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
      log(green(`✓`) + ` Copied agents/${agentFile}`);
      copiedAgents++;
    } else {
      log(yellow(`⚠`) + ` agents/${agentFile} not found — skipped`);
    }
  }

  // 4. Write cycle-state.json
  const state = {
    ...INITIAL_CYCLE_STATE,
    projectName,
    createdAt: today(),
  };
  fs.writeFileSync(
    path.join(projectDir, "cycle-state.json"),
    JSON.stringify(state, null, 2)
  );
  log(green(`✓`) + ` Created cycle-state.json`);

  // 5. Create .gitignore
  const gitignore = `.env\n.env.local\nnode_modules/\n.DS_Store\n`;
  fs.writeFileSync(path.join(projectDir, ".gitignore"), gitignore);
  log(green(`✓`) + ` Created .gitignore`);

  // 6. Print summary
  log("");
  log(bold(`🚀 Project "${projectName}" initialized`));
  log("");
  log(`  ${cyan("Structure:")}`)
  log(`  ${dirName}/`);
  log(`  ├── PLAN.md          ← Fill this in first`);
  log(`  ├── cycle-state.json ← Orchestrator reads this`);
  log(`  ├── .gitignore`);
  log(`  └── agents/`);
  for (const f of AGENT_FILES) {
    if (fs.existsSync(path.join(agentsDir, f))) {
      log(`      ├── ${f}`);
    }
  }
  log("");
  log(`  ${cyan("Next steps:")}`);
  log(`  1. cd ${dirName}`);
  log(`  2. Open PLAN.md and fill in every [TODO] field`);
  log(`  3. Pass PLAN.md to the Orchestrator agent (agents/agent-orchestrator.md)`);
  log(`  4. Orchestrator will dispatch PM → Design → Frontend+Backend → QA`);
  log("");
  log(`  ${cyan("Tip:")} Run the Orchestrator with:`);
  log(`  "Read cycle-state.json and agents/agent-orchestrator.md.`);
  log(`   The project is in phase: init. What should happen next?"`);
  log("");
}

main();
