#!/usr/bin/env node
/**
 * agent-init
 * Scaffolds a new agent-driven development project.
 * Usage: npx agent-init [project-name]
 *   or:  node agent-init.js [project-name]
 *
 * What it does:
 *   1. Creates project directory
 *   2. Generates PLAN.md from template (with date + project name pre-filled)
 *   3. Copies all agent prompt .md files into /agents/
 *   4. Creates cycle-state.json with initial state
 *   5. Prints next steps
 */

const fs = require("fs");
const path = require("path");

// ─── Config ──────────────────────────────────────────────────────────────────

const AGENT_FILES = [
  "agent-orchestrator.md",
  "agent-spec.md",
  "agent-arch.md",
  "agent-pm.md",
  "agent-design.md",
  "agent-frontend.md",
  "agent-backend.md",
  "agent-qa.md",
];

const ROOT_TEMPLATE_FILES = [
  { src: "orchestrate.template.js", dest: "orchestrate.js" },
  { src: "CLAUDE.template.md",      dest: "CLAUDE.md" },
  { src: "requirements.template.md", dest: "requirements.md" },
  { src: "use-cases.template.md",    dest: "use-cases.md" },
  { src: "adr.template.md",          dest: "adr/adr.template.md" },
  { src: "meeting.template.md",      dest: "meetings/meeting.template.md" },
  { src: "intake.template.md",       dest: "intake.md" },
];

const INITIAL_CYCLE_STATE = {
  phase: "init",
  completed: [],
  pending: ["spec"],
  blockers: [],
  checkpoints: {
    A: "pending",  // human approves scope + architecture before PM runs
    B: "pending",  // human approves sprint result before DONE
  },
  artifacts: {
    "intake.md": false,
    "requirements.md": false,
    "use-cases.md": false,
    "intent.md": false,
    "architecture-decision.md": false,
    "PLAN.md": false,
    "design-spec.md": false,
    "design-tokens.md": false,
    "api-spec.yaml": false,
    "api-samples.sh": false,
    "api-contract.md": false,
    "verify-report.json": false,
    "qa-report.md": false,
  },
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function today() {
  return new Date().toISOString().split("T")[0];
}

function colorize(text, code) {
  return `\x1b[${code}m${text}\x1b[0m`;
}

const green = (t) => colorize(t, "32");
const cyan = (t) => colorize(t, "36");
const yellow = (t) => colorize(t, "33");
const bold = (t) => colorize(t, "1");

function log(msg) {
  console.log(msg);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function main() {
  const projectName = process.argv[2];

  if (!projectName) {
    console.error("Usage: agent-init <project-name>");
    console.error("Example: agent-init my-todo-app");
    process.exit(1);
  }

  // Sanitize project name for directory
  const dirName = projectName
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");

  const projectDir = path.join(process.cwd(), dirName);
  const agentsDir = path.join(projectDir, "agents");
  const adrDir = path.join(projectDir, "adr");
  const meetingsDir = path.join(projectDir, "meetings");

  // 1. Create project directory
  if (fs.existsSync(projectDir)) {
    console.error(`Error: Directory "${dirName}" already exists.`);
    process.exit(1);
  }

  fs.mkdirSync(projectDir, { recursive: true });
  fs.mkdirSync(agentsDir, { recursive: true });
  fs.mkdirSync(adrDir, { recursive: true });
  fs.mkdirSync(meetingsDir, { recursive: true });
  log(green(`✓`) + ` Created ${dirName}/`);
  log(green(`✓`) + ` Created ${dirName}/agents/`);
  log(green(`✓`) + ` Created ${dirName}/adr/`);
  log(green(`✓`) + ` Created ${dirName}/meetings/`);

  // 2. Generate PLAN.md from template
  const templatePath = path.join(__dirname, "PLAN.template.md");

  let planContent;
  if (fs.existsSync(templatePath)) {
    planContent = fs.readFileSync(templatePath, "utf8");
  } else {
    // Inline minimal fallback if template not found
    planContent = `# PLAN.md — ${projectName}\n> Generated by agent-init on ${today()}\n\n## Overview\n[TODO]\n\n## Goals\n- [ ] [TODO]\n\n## User Stories\n[TODO]\n\n## Technical Constraints\n[TODO]\n`;
  }

  // Replace placeholder values
  planContent = planContent
    .replace("[Project Name]", projectName)
    .replace("[DATE]", today());

  fs.writeFileSync(path.join(projectDir, "PLAN.md"), planContent);
  log(green(`✓`) + ` Generated PLAN.md`);

  // 3. Copy agent prompt files
  let copiedAgents = 0;
  for (const agentFile of AGENT_FILES) {
    const src = path.join(__dirname, agentFile);
    const dest = path.join(agentsDir, agentFile);

    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
      log(green(`✓`) + ` Copied agents/${agentFile}`);
      copiedAgents++;
    } else {
      log(yellow(`⚠`) + ` agents/${agentFile} not found — skipped`);
    }
  }

  // 4. Copy root template files (orchestrate.js, CLAUDE.md)
  for (const { src, dest } of ROOT_TEMPLATE_FILES) {
    const srcPath = path.join(__dirname, src);
    const destPath = path.join(projectDir, dest);
    if (fs.existsSync(srcPath)) {
      fs.copyFileSync(srcPath, destPath);
      log(green(`✓`) + ` Copied ${dest}`);
    } else {
      log(yellow(`⚠`) + ` ${src} not found — skipped`);
    }
  }

  // 6. Write cycle-state.json
  const state = {
    ...INITIAL_CYCLE_STATE,
    projectName,
    createdAt: today(),
  };
  fs.writeFileSync(
    path.join(projectDir, "cycle-state.json"),
    JSON.stringify(state, null, 2)
  );
  log(green(`✓`) + ` Created cycle-state.json`);

  // 7. Create .gitignore
  const gitignore = `.env\n.env.local\nnode_modules/\n.DS_Store\n.current-agent\nlighthouse-report.json\n`;
  fs.writeFileSync(path.join(projectDir, ".gitignore"), gitignore);
  log(green(`✓`) + ` Created .gitignore`);

  // Write ADR index
  const adrIndex = [
    `# ADR Index — ${projectName}`,
    `> Architecture Decision Records accumulate here throughout the development cycle.`,
    `> Every agent writes ADRs for significant decisions. Run \`node orchestrate.js adr\` to list them.`,
    `>`,
    `> **Format:** \`ADR-NNN-[agent]-[topic].md\` — copy \`adr.template.md\` to start a new one.`,
    `> **Rule:** Update this table every time you add a new ADR file.`,
    ``,
    `| ID | Title | Author | Status | Date |`,
    `|----|-------|--------|--------|------|`,
    `| ADR-001 | Architecture Decision | Architecture Agent | pending | — |`,
    ``,
    `## Decision Categories`,
    ``,
    `| Category | Who writes it | Example topics |`,
    `|----------|--------------|----------------|`,
    `| Scope | Spec Agent | Out-of-scope cuts, assumption resolutions, priority changes |`,
    `| Architecture | Architecture Agent | System style, tech stack, integration patterns |`,
    `| Planning | PM Agent | Sprint deferrals, milestone ordering |`,
    `| Design | Design Agent | UX patterns, accessibility trade-offs, design deviations |`,
    `| Backend | Backend Agent | API design, data model, security, contract deviations |`,
    `| Frontend | Frontend Agent | State management, component patterns, design deviations |`,
    `| QA | QA Agent | Coverage exclusions, accepted bugs, waived contract violations |`,
  ].join("\n");
  fs.writeFileSync(path.join(adrDir, "ADR-000-index.md"), adrIndex);
  log(green(`✓`) + ` Created adr/ADR-000-index.md`);

  // 8. Print summary
  log("");
  log(bold(`🚀 Project "${projectName}" initialized`));
  log("");
  log(`  ${cyan("Structure:")}`);
  log(`  ${dirName}/`);
  log(`  ├── intake.md              ← Spec Agent fills this in FIRST (raw request + Q&A)`);
  log(`  ├── requirements.md       ← Spec Agent fills this in (after intake confirmed)`);
  log(`  ├── use-cases.md          ← Spec Agent fills this in`);
  log(`  ├── PLAN.md               ← PM Agent fills this in`);
  log(`  ├── orchestrate.js        ← Pipeline controller`);
  log(`  ├── CLAUDE.md             ← Claude Code auto-pipeline rules`);
  log(`  ├── cycle-state.json      ← Phase tracking`);
  log(`  ├── .gitignore`);
  log(`  ├── adr/`);
  log(`  │   └── ADR-000-index.md`);
  log(`  ├── meetings/`);
  log(`  │   └── meeting.template.md`);
  log(`  └── agents/`);
  for (const f of AGENT_FILES) {
    if (fs.existsSync(path.join(agentsDir, f))) {
      log(`      ├── ${f}`);
    }
  }
  log("");
  log(`  ${cyan("Next steps:")}`);
  log(`  1. cd ${dirName}`);
  log(`  2. Run the Spec Agent with your project request:`);
  log(`     → Hand agent-spec.md to Claude with your idea`);
  log(`     → It first writes intake.md (raw request + Q&A + confirmed intent)`);
  log(`     → Then produces: requirements.md, use-cases.md, intent.md`);
  log(`  3. Run the pipeline:`);
  log(`     node orchestrate.js run`);
  log(`  4. Or step by step:`);
  log(`     node orchestrate.js status`);
  log(`     node orchestrate.js validate <agent>`);
  log(`     node orchestrate.js advance <agent>`);
  log(`  5. When all agents complete:`);
  log(`     node orchestrate.js done`);
  log("");
  log(`  ${cyan("Pipeline order:")}`);
  log(`    spec → arch → [CHECKPOINT A] → pm`);
  log(`    → [KICKOFF MEETING] → design∥backend∥qa-planning`);
  log(`    → [CROSS-REVIEW MEETING] → frontend → qa-run`);
  log(`    → [SPRINT REVIEW MEETING] → [CHECKPOINT B] → done`);
  log(`  ${cyan("Tip:")} After frontend agent, run verify before advance:`);
  log(`     node orchestrate.js verify`);
  log("");
}

main();
