const fs = require("fs");
const path = require("path");

const AGENT_FILES = [
  "agent-orchestrator.md",
  "agent-spec.md",
  "agent-arch.md",
  "agent-pm.md",
  "agent-design.md",
  "agent-frontend.md",
  "agent-backend.md",
  "agent-qa.md",
];

const ROOT_TEMPLATE_FILES = [
  { src: "orchestrate.template.js", dest: "orchestrate.js" },
  { src: "CLAUDE.template.md", dest: "CLAUDE.md" },
  { src: "requirements.template.md", dest: "requirements.md" },
  { src: "use-cases.template.md", dest: "use-cases.md" },
  { src: "intent.template.md", dest: "intent.md" },
  { src: "adr.template.md", dest: "adr/adr.template.md" },
  { src: "meeting.template.md", dest: "meetings/meeting.template.md" },
  { src: "intake.template.md", dest: "intake.md" },
  { src: "sprint-backlog.template.md", dest: "sprint-backlog.md" },
  { src: "sprint-plan.template.md", dest: "sprint-plan.template.md" },
];

const INITIAL_CYCLE_STATE = {
  phase: "init",
  completed: [],
  pending: ["spec"],
  blockers: [],
  sprint: 1,
  sprintGoal: "",
  sprintStoriesPlanned: 0,
  sprintStoriesCompleted: 0,
  sprintHistory: [],
  checkpoints: {
    A: "pending",
    B: "pending",
  },
  meetings: {
    kickoff: {
      status: "pending",
      file: null,
      updatedAt: null,
    },
    "cross-review": {
      status: "pending",
      file: null,
      updatedAt: null,
    },
    "sprint-review": {
      status: "pending",
      file: null,
      updatedAt: null,
    },
  },
  artifacts: {
    "intake.md": false,
    "requirements.md": false,
    "use-cases.md": false,
    "intent.md": false,
    "architecture-decision.md": false,
    "PLAN.md": false,
    "sprint-backlog.md": false,
    "qa-plan.md": false,
    "design-spec.md": false,
    "design-tokens.md": false,
    "api-spec.yaml": false,
    "api-samples.sh": false,
    "schema.sql": false,
    "api-contract.md": false,
    "verify-report.json": false,
    "qa-report.md": false,
  },
};

function today() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function colorize(text, code) {
  return `\x1b[${code}m${text}\x1b[0m`;
}

const green = (t) => colorize(t, "32");
const cyan = (t) => colorize(t, "36");
const yellow = (t) => colorize(t, "33");
const bold = (t) => colorize(t, "1");

function log(msg) {
  console.log(msg);
}

function resolveProjectPaths(projectArg) {
  const looksLikePath =
    path.isAbsolute(projectArg) ||
    projectArg.includes(path.sep) ||
    projectArg.includes("/");

  if (!looksLikePath) {
    const dirName = projectArg
      .toLowerCase()
      .replace(/\s+/g, "-")
      .replace(/[^a-z0-9-]/g, "");

    return {
      projectDir: path.join(process.cwd(), dirName),
      dirName,
      projectLabel: projectArg,
    };
  }

  return {
    projectDir: path.resolve(projectArg),
    dirName: path.basename(path.resolve(projectArg)),
    projectLabel: path.basename(path.resolve(projectArg)),
  };
}

function initProject(projectName, options = {}) {
  const templateRoot = options.templateRoot || path.resolve(__dirname, "..");

  if (!projectName) {
    throw new Error("Usage: agent init <project-name>");
  }

  const { projectDir, dirName, projectLabel } = resolveProjectPaths(projectName);
  const agentsDir = path.join(projectDir, "agents");
  const adrDir = path.join(projectDir, "adr");
  const meetingsDir = path.join(projectDir, "meetings");

  if (fs.existsSync(projectDir)) {
    throw new Error(`Error: Directory "${projectDir}" already exists.`);
  }

  fs.mkdirSync(projectDir, { recursive: true });
  fs.mkdirSync(agentsDir, { recursive: true });
  fs.mkdirSync(adrDir, { recursive: true });
  fs.mkdirSync(meetingsDir, { recursive: true });
  log(green(`✓`) + ` Created ${dirName}/`);
  log(green(`✓`) + ` Created ${dirName}/agents/`);
  log(green(`✓`) + ` Created ${dirName}/adr/`);
  log(green(`✓`) + ` Created ${dirName}/meetings/`);

  const planTemplatePath = path.join(templateRoot, "PLAN.template.md");
  let planContent;
  if (fs.existsSync(planTemplatePath)) {
    planContent = fs.readFileSync(planTemplatePath, "utf8");
  } else {
    planContent = `# PLAN.md — ${projectName}\n> Generated by agent-init on ${today()}\n\n## Overview\n[TODO]\n`;
  }

  planContent = planContent
    .replace("[Project Name]", projectLabel)
    .replace("[DATE]", today());

  fs.writeFileSync(path.join(projectDir, "PLAN.md"), planContent);
  log(green(`✓`) + ` Generated PLAN.md`);

  for (const agentFile of AGENT_FILES) {
    const src = path.join(templateRoot, agentFile);
    const dest = path.join(agentsDir, agentFile);

    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
      log(green(`✓`) + ` Copied agents/${agentFile}`);
    } else {
      log(yellow(`⚠`) + ` agents/${agentFile} not found — skipped`);
    }
  }

  for (const { src, dest } of ROOT_TEMPLATE_FILES) {
    const srcPath = path.join(templateRoot, src);
    const destPath = path.join(projectDir, dest);
    if (fs.existsSync(srcPath)) {
      fs.copyFileSync(srcPath, destPath);
      log(green(`✓`) + ` Copied ${dest}`);
    } else {
      log(yellow(`⚠`) + ` ${src} not found — skipped`);
    }
  }

  const state = {
    ...INITIAL_CYCLE_STATE,
    projectName: projectLabel,
    createdAt: today(),
  };
  fs.writeFileSync(
    path.join(projectDir, "cycle-state.json"),
    JSON.stringify(state, null, 2)
  );
  log(green(`✓`) + ` Created cycle-state.json`);

  const gitignore = `.env\n.env.local\nnode_modules/\n.DS_Store\n.current-agent\n.agent/\nlighthouse-report.json\nverify-report.json\n`;
  fs.writeFileSync(path.join(projectDir, ".gitignore"), gitignore);
  log(green(`✓`) + ` Created .gitignore`);

  const adrIndex = [
    `# ADR Index — ${projectLabel}`,
    `> Architecture Decision Records accumulate here throughout the development cycle.`,
    `> Every agent writes ADRs for significant decisions. Run \`node orchestrate.js adr\` to list them.`,
    `>`,
    `> **Format:** \`ADR-NNN-[agent]-[topic].md\` — copy \`adr.template.md\` to start a new one.`,
    `> **Rule:** Update this table every time you add a new ADR file.`,
    ``,
    `| ID | Title | Author | Status | Date |`,
    `|----|-------|--------|--------|------|`,
    `| ADR-001 | Architecture Decision | Architecture Agent | pending | — |`,
    ``,
    `## Decision Categories`,
    ``,
    `| Category | Who writes it | Example topics |`,
    `|----------|--------------|----------------|`,
    `| Scope | Spec Agent | Out-of-scope cuts, assumption resolutions, priority changes |`,
    `| Architecture | Architecture Agent | System style, tech stack, integration patterns |`,
    `| Planning | PM Agent | Sprint deferrals, milestone ordering |`,
    `| Design | Design Agent | UX patterns, accessibility trade-offs, design deviations |`,
    `| Backend | Backend Agent | API design, data model, security, contract deviations |`,
    `| Frontend | Frontend Agent | State management, component patterns, design deviations |`,
    `| QA | QA Agent | Coverage exclusions, accepted bugs, waived contract violations |`,
  ].join("\n");
  fs.writeFileSync(path.join(adrDir, "ADR-000-index.md"), adrIndex);
  log(green(`✓`) + ` Created adr/ADR-000-index.md`);

  log("");
  log(bold(`🚀 Project "${projectLabel}" initialized`));
  log("");
  log(`  ${cyan("Next steps:")}`);
  log(`  1. cd ${dirName}`);
  log(`  2. Run ${bold("agent attach")} to connect Claude Code`);
  log(`  3. Run ${bold("agent dashboard")} for guided actions`);
  log(`  4. Run ${bold("agent run spec")} to start the first agent`);

  return { projectDir, dirName, projectLabel };
}

module.exports = {
  AGENT_FILES,
  ROOT_TEMPLATE_FILES,
  INITIAL_CYCLE_STATE,
  initProject,
  resolveProjectPaths,
  today,
};
